#!/bin/bash

if [ -e .suffix ]; then
    export IMAGE_SUFFIX=$(<.suffix)
    echo IMAGE_SUFFIX=$IMAGE_SUFFIX
fi

image=getup-engine${IMAGE_SUFFIX}:${1:-v3.9}
dockerfile=Dockerfile-${1:-v3.9}

echo "---> Building $image from $dockerfile"

[ "${NO_PULL}" != 1 ] && git pull
sudo docker build . -t $image -f $dockerfile
