#!/bin/bash

if [ -e .suffix ]; then
    export IMAGE_SUFFIX=$(<.suffix)
fi

export NO_PULL=1
git pull
sleep 2

releases="v3.9 v3.10"
latest=${releases##* }
for release in $releases; do
    (
        rcolor=$(tput sgr0)
        color=$(tput sgr0 && tput setaf ${release#*.})
        ./build $release 2>&1 | sed -e "s/\(.*\)/${color}\1${rcolor}/"
    ) &
done

kill_bg_jobs()
{
    local pids=$(jobs -lr | awk '{print $2}')
    if [ -z "$pids" ]; then
        return
    fi
    echo "Killing background jobs ($pids)"
    kill -INT $pids
}

trap kill_bg_jobs SIGINT
wait
trap - SIGINT

tput sgr0 && tput setaf 10 && tput bold
echo
echo

tput sgr0
image_name=getup-engine${IMAGE_SUFFIX}
echo "---> Tagging: $image_name:$latest as $image_name:latest"
docker tag $image_name:$latest $image_name:latest
