FROM openshift/origin-ansible:v3.6

USER root

ENV PACKER_VERSION=1.2.3 \
    TERRAFORM_VERSION=0.11.3 \
    TARGET_OPENSHIFT_RELEASE=v3.6 \
    TARGET_OPENSHIFT_VERSION=3.6.1 \
    PATH=/getup-engine/bin/:$PATH

COPY yum.repos.d/*.repo /etc/yum.repos.d/

RUN rpm --import https://packages.microsoft.com/keys/microsoft.asc && \
    yum install -y gettext unzip sudo bind-utils azure-cli python2-pip google-cloud-sdk which && \
    yum clean all && \
    pip install --upgrade pip && \
    pip install awscli && \
    mkdir -p /getup-engine/bin && \
    ln -s /usr/share/ansible/openshift-ansible /openshift-ansible

RUN curl -O https://releases.hashicorp.com/packer/${PACKER_VERSION}/packer_${PACKER_VERSION}_linux_amd64.zip && \
    unzip packer_${PACKER_VERSION}_linux_amd64.zip -d /getup-engine/bin/ && \
    rm -f packer_${PACKER_VERSION}_linux_amd64.zip

RUN curl -O https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip && \
    unzip terraform_${TERRAFORM_VERSION}_linux_amd64.zip -d /getup-engine/bin/ && \
    rm -f terraform_${TERRAFORM_VERSION}_linux_amd64.zip

RUN echo '#1000 ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers.d/allow_local_action && \
    ln -s /state/azure ~/.azure && \
    cd /getup-engine && \
    git clone https://github.com/Neilpang/acme.sh.git && \
    cd ./acme.sh && \
    ./acme.sh --install --force --nocron

ADD images/ /getup-engine/images
ADD terraform/ /getup-engine/terraform

RUN for provider in /getup-engine/terraform/*/ /getup-engine/images/azure/; \
    do cd $provider && terraform init || exit 1; done

ADD ansible /getup-engine/ansible

ADD bin/ /getup-engine/bin/

RUN chmod -R go+rw /getup-engine

WORKDIR /getup-engine

USER 1000

ENTRYPOINT [ "/getup-engine/bin/entrypoint" ]

CMD [ "/bin/bash" ]
