FROM getupcloud/origin-ansible:v3.9

USER root

ENV PACKER_VERSION=1.2.5 \
    TERRAFORM_VERSION=0.11.8 \
    TARGET_OPENSHIFT_RELEASE=v3.9 \
    TARGET_OPENSHIFT_VERSION=3.9.0 \
    PATH=/getup-engine/bin/:$PATH \
    PACKER_BIN=/getup-engine/bin/packer \
    TERRAFORM_BIN=/getup-engine/bin/terraform \
    TF_DATA_DIR=/state/.terraform \
    ANSIBLE_BIN=/usr/bin/ansible \
    ANSIBLE_PLAYBOOK_BIN=/usr/bin/ansible-playbook

COPY yum.repos.d/*.repo /etc/yum.repos.d/

RUN rpm --import https://packages.microsoft.com/keys/microsoft.asc && \
    yum install -y gettext unzip sudo bind-utils azure-cli python2-pip google-cloud-sdk which patch git && \
    yum clean all && \
    pip install --upgrade pip && \
    pip install awscli pyaml && \
    mkdir -p /getup-engine/bin && \
    ln -s /usr/share/ansible/openshift-ansible /openshift-ansible && \
    \
    curl -O https://releases.hashicorp.com/packer/${PACKER_VERSION}/packer_${PACKER_VERSION}_linux_amd64.zip && \
    unzip packer_${PACKER_VERSION}_linux_amd64.zip -d /getup-engine/bin/ && \
    rm -f packer_${PACKER_VERSION}_linux_amd64.zip && \
    \
    curl -O https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip && \
    unzip terraform_${TERRAFORM_VERSION}_linux_amd64.zip -d /getup-engine/bin/ && \
    rm -f terraform_${TERRAFORM_VERSION}_linux_amd64.zip && \
    \
    echo '#1000 ALL=(ALL) NOPASSWD: ALL' >> /etc/sudoers.d/allow_local_action && \
    ln -s /state/azure ~/.azure && \
    cd /getup-engine && \
    git clone https://github.com/Neilpang/acme.sh.git && \
    cd ./acme.sh && \
    ./acme.sh --install --force --nocron && \
    curl -L https://github.com/jmespath/jp/releases/download/0.1.2/jp-linux-amd64 > /getup-engine/bin/jp

## Workaround: prometheus listens on 0.0.0.0:9090 in order for
## grafana to reach it when on proxy-mode
RUN sed -ie \
    's/--web.listen-address=localhost:9090/--web.listen-address=0.0.0.0:9090/' \
    /usr/share/ansible/openshift-ansible/roles/openshift_prometheus/templates/prometheus.j2

WORKDIR /getup-engine

ENTRYPOINT [ "/getup-engine/bin/entrypoint" ]

CMD [ "/bin/bash" ]

ADD images/ /getup-engine/images
ADD terraform/ /getup-engine/terraform
ADD state-backend/ /getup-engine/state-backend

RUN for provider in /getup-engine/terraform/*/ /getup-engine/images/azure/; do \
      echo "Terraform init [$provider]" && \
      cd $provider && \
      terraform init -upgrade -reconfigure -input=false || exit 1; \
    done

ADD ansible /getup-engine/ansible

RUN cd / && \
    for i in /getup-engine/ansible/patches/${TARGET_OPENSHIFT_RELEASE}-*.diff; do \
        [ -e "${i}" ] && patch -p0 < "$i"; \
    done

ADD bin/ /getup-engine/bin/

ARG RELEASE

RUN chmod -R ug+rw,o-w /getup-engine && \
    chmod -R +x /getup-engine/bin/ && \
    chown -R 1001 /getup-engine/* && \
    echo $RELEASE > /getup-engine/release

USER 1000
