#!/bin/bash

cluster_name=$1
shift

if [ -z "${cluster_name}" ]; then
    exec docker ps --format "{{.Names}}" | \grep ^getup-engine- | sed -e 's/^getup-engine-//' | sort
fi

exec sudo docker exec -it getup-engine-$cluster_name entrypoint ${@:-bash}
