#!/bin/bash

cluster_name=$1
shift

if [ -z "${cluster_name}" ]; then
    exec docker ps --format "{{.Names}}" | \grep ^getup-engine- | sed -e 's/^getup-engine${IMAGE_SUFFIX}-//' | sort
fi

exec sudo docker exec -it getup-engine${IMAGE_SUFFIX}-$cluster_name entrypoint ${@:-bash}
