#!/bin/bash

cluster_name=${1}
shift

if [ -d "${cluster_name}" ]; then
    state_dir=$(realpath ${cluster_name})
else
    state_dir=$(realpath ./state/${cluster_name})
fi

if [ -e $state_dir/.suffix ]; then
    export IMAGE_SUFFIX=$(<$state_dir/.suffix)
    echo IMAGE_SUFFIX=$IMAGE_SUFFIX
elif [ -e .suffix ]; then
    export IMAGE_SUFFIX=$(<.suffix)
    echo IMAGE_SUFFIX=$IMAGE_SUFFIX
fi

if [ -z "${cluster_name}" ]; then
    exec docker ps --format "{{.Names}}" | \grep ^getup-engine- | sed -e 's/^getup-engine${IMAGE_SUFFIX}-//' | sort
fi

exec sudo docker exec -it getup-engine${IMAGE_SUFFIX}-$cluster_name entrypoint ${@:-bash}
