#!/bin/bash

set -e

version=v3.9

if [ $# -lt 1 ]; then
    echo "Usage: $0 cluster-name [version=$version] [docker-run-options...]"
    exit 0
fi

cluster_name=${1}
shift

if [ -d "${cluster_name}" ]; then
    state_dir=$(realpath ${cluster_name})
else
    state_dir=$(realpath ./state/${cluster_name})
fi

if [ -e $state_dir/.suffix ]; then
    export IMAGE_SUFFIX=$(<$state_dir/.suffix)
    echo IMAGE_SUFFIX=$IMAGE_SUFFIX
elif [ -e .suffix ]; then
    export IMAGE_SUFFIX=$(<.suffix)
    echo IMAGE_SUFFIX=$IMAGE_SUFFIX
fi

name=${state_dir##*/}
container_name=getup-engine${IMAGE_SUFFIX}-${name}

if [ $# -gt 0 ]; then
    image=getup-engine${IMAGE_SUFFIX}:${1}
    shift
else
    image=getup-engine${IMAGE_SUFFIX}:$version
fi

if ! [ -d "$state_dir" ]; then
    echo Invalid state dir: $state_dir
    exit 1
fi

echo
echo "Image:     $image"
echo "Container: $container_name"
echo "State dir: $state_dir"
echo

# Read id_rsa content

if [ -z "${ID_RSA}" ]; then
    if [ -r "${ID_RSA_FILE}" ]; then
        ID_RSA="$(<$ID_RSA_FILE)"
    elif [ -r "$state_dir/id_rsa" ]; then
        ID_RSA="$(<$state_dir/id_rsa)"
    elif [ -r "~/.ssh/id_rsa" ]; then
        ID_RSA="$(<~/.ssh/id_rsa)"
    else
        echo "Missing ssh private key"
        exit 1
    fi
fi

# Prepend cluster search domain
eval cluster_zone=$(awk -F= '/^CLUSTER_ZONE=/{print $2}' ${state_dir}/getupengine.env 2>/dev/null)
search=$(grep search /etc/resolv.conf | cut -f2- -d' ')

# setup permissions
if [ $(command -v chcon) ]; then
    sudo chcon -R -t svirt_sandbox_file_t ${state_dir}
fi
if [ $(id -u 1000 2> /dev/null ) ]; then
    sudo chown 1000 -R ${state_dir}
fi

sudo chgrp -R $(id -g) ${state_dir}

echo "---> Starting container ${container_name} from image $image"
sudo docker run -it --rm $@ \
    -v ${state_dir}/:/state \
    --env-file ${state_dir}/getupengine.env \
    -e "ID_RSA=${ID_RSA}" \
    --name ${container_name} \
    ${cluster_zone:+--dns-search $cluster_zone} \
    $(for dom in $search; do [ $cluster_zone != $dom ] && echo --dns-search $dom; done) \
    $image bash
