#!/bin/bash

source /etc/profile.d/etcdctl.sh

set -eu

ROOT_DIR=${0%/*}
PROVIDER=${1}
TIMESTAMP=$(date +%Y%m%d-%H%M%S-%Z)
BACKUP_ROOT=$(mktemp -d /tmp/cluster-backup-XXXXXX)
BACKUP_DIR=${BACKUP_ROOT}/etcd-backup-${TIMESTAMP}
BACKUP_FILE=${BACKUP_DIR}/etcd-backup-${TIMESTAMP}.tar.gz

cleanup()
{
    echo "--> Cleaning $BACKUP_ROOT"
    rm -rf $BACKUP_ROOT
}

warn()
{
    echo "--> Upload failed"
    echo "--> Backup files still in $BACKUP_ROOT"
}

trap cleanup EXIT

echo "--> Started" `date`
echo "--> Generating etcd backup to ${BACKUP_FILE}"

mkdir -p $BACKUP_DIR

etcdctl3 snapshot save $BACKUP_DIR/db
rsync --recursive /etc/etcd $BACKUP_DIR
rsync --recursive /etc/origin/master $BACKUP_DIR
rsync --recursive /etc/origin/node $BACKUP_DIR

cd $BACKUP_DIR
tar czvf $BACKUP_FILE db */ --atime-preserve --preserve-permissions

bash -c "${ROOT_DIR}/upload-${PROVIDER} ${BACKUP_FILE}" || trap warn EXIT

echo "--> Finished" `date`
